name: Build and Publish Wheels

on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  build-linux-x86_64:
    name: Linux Python x86_64 ${{ matrix.python-version }} - Build Wheels
    runs-on: ubuntu-latest
    container: keenon/diffdart:base
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
        include:
          - python-version: 3.6
            PYTHON_VERSION_CODE: cp36-cp36m
            PYTHON_VERSION_NUMBER: 3.6
            PYTHON: /opt/python/cp36-cp36m/bin/python3.6
            PYTHON_PATH: /opt/python/cp36-cp36m/bin/
            PYTHON_INCLUDE: /opt/python/cp36-cp36m/include/python3.6m/
            PYTHON_LIB: /opt/python/cp36-cp36m/lib/python3.6
          - python-version: 3.7
            PYTHON_VERSION_CODE: cp37-cp37m
            PYTHON_VERSION_NUMBER: 3.7
            PYTHON: /opt/python/cp37-cp37m/bin/python3.7
            PYTHON_PATH: /opt/python/cp37-cp37m/bin/
            PYTHON_INCLUDE: /opt/python/cp37-cp37m/include/python3.7m/
            PYTHON_LIB: /opt/python/cp37-cp37m/lib/python3.7
          - python-version: 3.8
            PYTHON_VERSION_CODE: cp38-cp38
            PYTHON_VERSION_NUMBER: 3.8
            PYTHON: /opt/python/cp38-cp38/bin/python3.8
            PYTHON_PATH: /opt/python/cp38-cp38/bin/
            PYTHON_INCLUDE: /opt/python/cp38-cp38/include/python3.8/
            PYTHON_LIB: /opt/python/cp38-cp38/lib/python3.8
          - python-version: 3.9
            PYTHON_VERSION_CODE: cp39-cp39
            PYTHON_VERSION_NUMBER: 3.9
            PYTHON: /opt/python/cp39-cp39/bin/python3.9
            PYTHON_PATH: /opt/python/cp39-cp39/bin/
            PYTHON_INCLUDE: /opt/python/cp39-cp39/include/python3.9/
            PYTHON_LIB: /opt/python/cp39-cp39/lib/python3.9
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set variables
        run: |
          VER=$(cat ./VERSION.txt)
          echo "VERSION=$VER"
          echo "VERSION=$VER" >> $GITHUB_ENV
      - name: Test environment
        run: |
          echo "VERSION=${{ env.VERSION }}"
          echo "PYTHON_VERSION_CODE=${{ matrix.PYTHON_VERSION_CODE }}"
          echo "PYTHON_VERSION_NUMBER=${{ matrix.PYTHON_VERSION_NUMBER }}"
      - name: Install pytest, wheel and auditwheel
        run: ${{ matrix.PYTHON }} -m pip install pytest wheel auditwheel
      - name: Install Pybind11 for this Python version
        run: |
          git clone https://github.com/pybind/pybind11.git
          pushd pybind11
          mkdir build
          pushd build
          PATH="${{ matrix.PYTHON_PATH }}:${PATH}" CPATH="${{ matrix.PYTHON_INCLUDE }}" cmake ..
          PATH="${{ matrix.PYTHON_PATH }}:${PATH}" CPATH="${{ matrix.PYTHON_INCLUDE }}" make install -j2
        env:
          PYTHON: ${{ matrix.PYTHON }}
          PYTHON_VERSION: ${{ matrix.PYTHON_VERSION_CODE }}
          PYTHON_INCLUDE: ${{ matrix.PYTHON_INCLUDE }}
          PYTHON_LIB: ${{ matrix.PYTHON_LIB }}
          PYTHON_VERSION_NUMBER: ${{ matrix.PYTHON_VERSION_NUMBER }}
      - name: Build wheel
        run: |
          PATH="${{ matrix.PYTHON_PATH }}:${PATH}" CPATH="${{ matrix.PYTHON_INCLUDE }}" ${{ matrix.PYTHON }} setup.py sdist bdist_wheel
          PATH="${{ matrix.PYTHON_PATH }}:${PATH}" CPATH="${{ matrix.PYTHON_INCLUDE }}" ${{ matrix.PYTHON }} -m auditwheel repair dist/nimblephysics-${{ env.VERSION }}-${{ matrix.PYTHON_VERSION_CODE }}-linux_x86_64.whl
        env:
          PYTHON: ${{ matrix.PYTHON }}
          PYTHON_VERSION: ${{ matrix.PYTHON_VERSION_CODE }}
          PYTHON_INCLUDE: ${{ matrix.PYTHON_INCLUDE }}
          PYTHON_LIB: ${{ matrix.PYTHON_LIB }}
          PYTHON_VERSION_NUMBER: ${{ matrix.PYTHON_VERSION_NUMBER }}
      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: nimblephysics-${{ env.VERSION }}-${{ matrix.PYTHON_VERSION_CODE }}-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
          path: wheelhouse/nimblephysics-${{ env.VERSION }}-${{ matrix.PYTHON_VERSION_CODE }}-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  build-linux-aarch64:
    name: Linux Python aarch64 ${{ matrix.python-version }} - Build Wheels
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
        include:
          - python-version: 3.6
            PYTHON_VERSION_CODE: cp36-cp36m
            PYTHON_VERSION_NUMBER: 3.6
            PYTHON: /opt/python/cp36-cp36m/bin/python3.6
            PYTHON_PATH: /opt/python/cp36-cp36m/bin/
            PYTHON_INCLUDE: /opt/python/cp36-cp36m/include/python3.6m/
            PYTHON_LIB: /opt/python/cp36-cp36m/lib/python3.6
          - python-version: 3.7
            PYTHON_VERSION_CODE: cp37-cp37m
            PYTHON_VERSION_NUMBER: 3.7
            PYTHON: /opt/python/cp37-cp37m/bin/python3.7
            PYTHON_PATH: /opt/python/cp37-cp37m/bin/
            PYTHON_INCLUDE: /opt/python/cp37-cp37m/include/python3.7m/
            PYTHON_LIB: /opt/python/cp37-cp37m/lib/python3.7
          - python-version: 3.8
            PYTHON_VERSION_CODE: cp38-cp38
            PYTHON_VERSION_NUMBER: 3.8
            PYTHON: /opt/python/cp38-cp38/bin/python3.8
            PYTHON_PATH: /opt/python/cp38-cp38/bin/
            PYTHON_INCLUDE: /opt/python/cp38-cp38/include/python3.8/
            PYTHON_LIB: /opt/python/cp38-cp38/lib/python3.8
          - python-version: 3.9
            PYTHON_VERSION_CODE: cp39-cp39
            PYTHON_VERSION_NUMBER: 3.9
            PYTHON: /opt/python/cp39-cp39/bin/python3.9
            PYTHON_PATH: /opt/python/cp39-cp39/bin/
            PYTHON_INCLUDE: /opt/python/cp39-cp39/include/python3.9/
            PYTHON_LIB: /opt/python/cp39-cp39/lib/python3.9
    steps:
      - name: Install QEMU deps
        run: |
          sudo apt-get update -q -y
          sudo apt-get -qq install -y qemu qemu-user-static
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes --credential yes
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set variables
        run: |
          VER=$(cat ./VERSION.txt)
          echo "VERSION=$VER"
          echo "VERSION=$VER" >> $GITHUB_ENV
      - name: Test environment
        run: |
          echo "VERSION=${{ env.VERSION }}"
          echo "PYTHON_VERSION_CODE=${{ matrix.PYTHON_VERSION_CODE }}"
          echo "PYTHON_VERSION_NUMBER=${{ matrix.PYTHON_VERSION_NUMBER }}"
      - name: Run docker build
        run: |
          docker run --rm --tty keenon/diffdart:base_aarch64 /bin/bash -c '\
          VER=$(cat ./VERSION.txt);\
          PYTHON=${{ matrix.PYTHON }};\
          PYTHON_VERSION=${{ matrix.PYTHON_VERSION_CODE }};\
          PYTHON_INCLUDE=${{ matrix.PYTHON_INCLUDE }};\
          PYTHON_LIB=${{ matrix.PYTHON_LIB }};\
          PYTHON_VERSION_NUMBER=${{ matrix.PYTHON_VERSION_NUMBER }};\
          echo "VERSION=$VER";\
          echo "VERSION=$VER" >> $GITHUB_ENV;\
          ${{ matrix.PYTHON }} -m pip install pytest wheel auditwheel;\
          git clone https://github.com/pybind/pybind11.git;\
          pushd pybind11;\
          mkdir build;\
          pushd build;\
          PATH="${{ matrix.PYTHON_PATH }}:${PATH}" CPATH="${{ matrix.PYTHON_INCLUDE }}" cmake ..;\
          PATH="${{ matrix.PYTHON_PATH }}:${PATH}" CPATH="${{ matrix.PYTHON_INCLUDE }}" make install -j2;\
          PATH="${{ matrix.PYTHON_PATH }}:${PATH}" CPATH="${{ matrix.PYTHON_INCLUDE }}" ${{ matrix.PYTHON }} setup.py sdist bdist_wheel;\
          PATH="${{ matrix.PYTHON_PATH }}:${PATH}" CPATH="${{ matrix.PYTHON_INCLUDE }}" ${{ matrix.PYTHON }} -m auditwheel repair dist/nimblephysics-${{ env.VERSION }}-${{ matrix.PYTHON_VERSION_CODE }}-linux_aarch64.whl;\
          '
      - name: Copy artifact back
        run: |
          docker cp $(docker ps -alq)/wheelhouse .
      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: nimblephysics-${{ env.VERSION }}-${{ matrix.PYTHON_VERSION_CODE }}-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
          path: wheelhouse/nimblephysics-${{ env.VERSION }}-${{ matrix.PYTHON_VERSION_CODE }}-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
  build-mac:
    name: Mac OSX Python ${{ matrix.python-version }} - Build Wheels
    runs-on: macos-10.15
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
        include:
          - python-version: 3.6
            PYTHON_VERSION_CODE: cp36-cp36m
            MAC_VERSION_TAG: macosx_10_14
          - python-version: 3.7
            PYTHON_VERSION_CODE: cp37-cp37m
            MAC_VERSION_TAG: macosx_10_14
          - python-version: 3.8
            PYTHON_VERSION_CODE: cp38-cp38
            MAC_VERSION_TAG: macosx_10_14
          - python-version: 3.9
            PYTHON_VERSION_CODE: cp39-cp39
            MAC_VERSION_TAG: macosx_10_15
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Select Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: "x64" # optional x64 or x86. Defaults to x64 if not specified
      - name: Set variables
        run: |
          VER=$(cat ./VERSION.txt)
          echo "VERSION=$VER"
          echo "VERSION=$VER" >> $GITHUB_ENV
      - name: Test environment
        run: |
          echo "VERSION=${{ env.VERSION }}"
          echo "PYTHON_VERSION_CODE=${{ matrix.PYTHON_VERSION_CODE }}"
      - name: Install pytest, wheel and auditwheel
        run: python -m pip install pytest wheel auditwheel
      - name: Install dependencies
        run: ci/mac/install_dependencies.sh
      - name: Build wheel
        run: |
          cd ci/mac
          ./build_wheels.sh
      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: nimblephysics-${{ env.VERSION }}-${{ matrix.PYTHON_VERSION_CODE }}-${{ matrix.MAC_VERSION_TAG }}_x86_64.whl
          path: wheelhouse/nimblephysics-${{ env.VERSION }}-${{ matrix.PYTHON_VERSION_CODE }}-${{ matrix.MAC_VERSION_TAG }}_x86_64.whl
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: [build-linux-x86_64, build-linux-aarch64, build-mac]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: wheelhouse
      - name: Display structure of downloaded files before flattening
        run: ls -R
        working-directory: wheelhouse
      - name: Flatten files
        run: |
          mkdir wheelhouse2
          find wheelhouse -type f -exec mv {} wheelhouse2 \;
          rm -rf wheelhouse
          mv wheelhouse2 wheelhouse
      - name: Display structure of downloaded files after flattening
        run: ls -R
        working-directory: wheelhouse
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: wheelhouse/
          skip_existing: true
          verbose: true
